export type Job = {
  id: number;
  company: string;
  title: string;
  location: string;
  founded: string;
  size: string;
  description: string;
  tags: string[];
  logoText: string;
  logoTone: "green" | "red" | "blue" | "teal" | "purple" | "dark";
  experience: string;
  recruiter: string;
  recruiterRole: string;
};

export const jobs: Job[] = [
  {
    id: 1,
    company: "AblyWorks",
    title: "Fullstack Engineer",
    location: "Noida",
    founded: "2017",
    size: "50 - 200 employees",
    description:
      "AblyWorks is an HR-tech company that offers AI-powered HR and business software tools to help organizations automate hiring, communication and employee workflows.",
    tags: ["Node.js", "React.js", "JavaScript", "Express.js", "HTML", "MongoDB"],
    logoText: "A",
    logoTone: "green",
    experience: "1 - 5 years",
    recruiter: "Preksha Trivedi",
    recruiterRole: "Talent Acquisition Specialist at Hrizen",
  },
  {
    id: 2,
    company: "Adobe",
    title: "Technical Support Consultant - Analytics",
    location: "Noida",
    founded: "1982",
    size: "More than 1000 employees",
    description:
      "Founded in 1982 and headquartered in San Jose, Adobe has historically focused on the creation of multimedia and creativity software products.",
    tags: ["HTML", "JavaScript", "CSS", "Customer Service", "Game Development"],
    logoText: "A",
    logoTone: "red",
    experience: "0 - 3 years",
    recruiter: "Neha Sharma",
    recruiterRole: "Recruiting Partner at Adobe",
  },
  {
    id: 3,
    company: "Younovate Labs",
    title: "Full Stack Developer",
    location: "Bangalore",
    founded: "2024",
    size: "0 - 10 employees",
    description:
      "Younovate is an AI-driven career guidance platform that offers psychometric tests, personalized career recommendations, tools and expert support.",
    tags: ["JavaScript", "Node.js", "React.js", "Laravel", "Next.js", "PHP"],
    logoText: "YL",
    logoTone: "dark",
    experience: "2 - 5 years",
    recruiter: "Ritika Jain",
    recruiterRole: "Founder Office at Younovate Labs",
  },
  {
    id: 4,
    company: "RIU.ai",
    title: "Fullstack Engineer",
    location: "Bangalore",
    founded: "2023",
    size: "0 - 10 employees",
    description:
      "RIU is an AI-based SaaS platform that provides automated solutions for ESG reporting, carbon accounting, compliance management and net-zero planning.",
    tags: ["JavaScript", "Express.js", "Node.js", "React.js", "Algorithms"],
    logoText: "RIU",
    logoTone: "teal",
    experience: "2 - 6 years",
    recruiter: "Aditi Rao",
    recruiterRole: "People Operations at RIU.ai",
  },
  {
    id: 5,
    company: "Rinovea",
    title: "Software Engineer",
    location: "Pune",
    founded: "2025",
    size: "10 - 50 employees",
    description:
      "Rinovea is a technology company expert in GCC setup, agile development, cloud-native engineering and digital transformation delivery.",
    tags: ["JavaScript", "Node.js", "Angular"],
    logoText: "R",
    logoTone: "red",
    experience: "1 - 4 years",
    recruiter: "Kavya Singh",
    recruiterRole: "Hiring Specialist at Rinovea",
  },
  {
    id: 6,
    company: "Medront",
    title: "Full Stack Engineer",
    location: "Work From Home",
    founded: "2020",
    size: "0 - 10 employees",
    description:
      "Medront is a secure data platform that provides seamless access by synchronizing data from major platforms like Android, Facebook and health systems.",
    tags: ["JavaScript", "Express.js", "Node.js", "React.js"],
    logoText: "M",
    logoTone: "blue",
    experience: "2 - 5 years",
    recruiter: "Vivek Nair",
    recruiterRole: "Talent Partner at Medront",
  },
  {
    id: 7,
    company: "OSYTE",
    title: "Full Stack Developer",
    location: "Chennai",
    founded: "2018",
    size: "0 - 10 employees",
    description:
      "OSYTE is an investment technology company providing institutional client data management and investment management products.",
    tags: ["JavaScript", "Node.js", "React.js", "Java", "Python", "Angular"],
    logoText: "OS",
    logoTone: "blue",
    experience: "1 - 5 years",
    recruiter: "Meera Thomas",
    recruiterRole: "Recruiter at OSYTE",
  },
  {
    id: 8,
    company: "QRisTix",
    title: "SDE - 2",
    location: "Bangalore",
    founded: "2021",
    size: "10 - 50 employees",
    description:
      "QRisTix is software made for equipment and rental businesses. It offers easy-to-use tools to run a business from anywhere.",
    tags: ["JavaScript", "Node.js", "Angular"],
    logoText: "QR",
    logoTone: "blue",
    experience: "3 - 6 years",
    recruiter: "Sana Khan",
    recruiterRole: "Recruiting Lead at QRisTix",
  },
  {
    id: 9,
    company: "Atomz AI",
    title: "Full Stack Engineer",
    location: "Work From Home",
    founded: "2024",
    size: "0 - 10 employees",
    description:
      "Atomz.ai is an AI-powered product discovery and search optimization platform for ecommerce and D2C brands.",
    tags: ["Node.js", "Golang", "Python"],
    logoText: "az",
    logoTone: "purple",
    experience: "2 - 6 years",
    recruiter: "Rohit Malhotra",
    recruiterRole: "Co-founder at Atomz AI",
  },
  {
    id: 10,
    company: "DocEngage",
    title: "Software Development Engineer - I",
    location: "Work From Home",
    founded: "2010",
    size: "10 - 50 employees",
    description:
      "DocEngage is a healthcare applications platform that offers 30+ apps with flagship products for practice management, EHR, CRM and radiology workflows.",
    tags: ["React.js", "Node.js", "JavaScript", "Algorithms", "Data Structures"],
    logoText: "D",
    logoTone: "green",
    experience: "1 - 4 years",
    recruiter: "Ananya Bose",
    recruiterRole: "Talent Acquisition at DocEngage",
  },
  {
    id: 11,
    company: "Elivaas",
    title: "Software Engineer I - Backend",
    location: "Gurgaon",
    founded: "2021",
    size: "10 - 50 employees",
    description:
      "Elivaas is a tech-driven villa and luxury apartment management system that helps owners monetize, monitor and maintain vacation homes.",
    tags: ["Node.js", "Express.js"],
    logoText: "E",
    logoTone: "dark",
    experience: "1 - 3 years",
    recruiter: "Harshita Soni",
    recruiterRole: "People Team at Elivaas",
  },
  {
    id: 12,
    company: "NobleProg",
    title: "Full Stack Developer",
    location: "Work From Home",
    founded: "2005",
    size: "50 - 200 employees",
    description:
      "NobleProg is a global training and consultancy firm that has trained professionals from organizations across classroom and remote learning programs.",
    tags: ["Node.js", "C", "PHP", "Python"],
    logoText: "NP",
    logoTone: "blue",
    experience: "2 - 5 years",
    recruiter: "Dhruv Patel",
    recruiterRole: "Technical Recruiter at NobleProg",
  },
  {
    id: 13,
    company: "Adobe",
    title: "Technical Support Consultant",
    location: "Noida",
    founded: "1982",
    size: "More than 1000 employees",
    description:
      "Adobe creates products and services used globally for content creation, analytics, campaign management and digital experiences.",
    tags: ["HTML", "JavaScript", "CSS", "SQL"],
    logoText: "A",
    logoTone: "red",
    experience: "0 - 3 years",
    recruiter: "Neha Sharma",
    recruiterRole: "Recruiting Partner at Adobe",
  },
  {
    id: 14,
    company: "CyberNest",
    title: "Full Stack Engineer",
    location: "Work From Home",
    founded: "2026",
    size: "10 - 50 employees",
    description:
      "CyberNest is an IT solutions company focused on making technology accessible to small and medium businesses across Canada.",
    tags: ["JavaScript", "Node.js", "React.js", "Golang", "Python", "Angular"],
    logoText: "CN",
    logoTone: "dark",
    experience: "2 - 7 years",
    recruiter: "Isha Kapoor",
    recruiterRole: "Talent Partner at CyberNest",
  },
  {
    id: 15,
    company: "GTEN",
    title: "Fullstack Developer",
    location: "Mumbai",
    founded: "2010",
    size: "50 - 200 employees",
    description:
      "GTEN is a global digital transformation consulting firm providing full-stack development, automation and product engineering solutions.",
    tags: ["React.js", "Node.js", "HTML", "JavaScript", "TypeScript", "CSS"],
    logoText: "G",
    logoTone: "blue",
    experience: "2 - 5 years",
    recruiter: "Pranay Menon",
    recruiterRole: "Recruitment Manager at GTEN",
  },
];
